#define AL_ERROR             -1
#define AL_INTERNAL          -2
#define AL_LOWMEM            -3
#define AL_FILNF             -4
#define AL_FILE_CREATE       -5
#define AL_FILE_READ         -6
#define AL_FILE_WRITE        -7
#define AL_FILE_CLOSE        -8
#define AL_HELP_KEYWORD      -9
#define AL_LINE_NOT_FOUND    -10
#define AL_BAD_ERROR_MSG     -11
#define AL_NO_MORE_WINDS     -12
#define AL_WINDOW_READONLY   -13
#define AL_FILE_DELETE       -14
#define AL_FILE_RENAME       -15
#define AL_EMPTY_NAME        -16
#define AL_ILLEGAL_NAME      -17
#define AL_ILLEGAL_NUMBER    -18
#define AL_BAD_CONFIG        -21
#define AL_CREATE_CONFIG     -22
#define AL_BAD_HELPFILE      -23
#define AL_HELP_NOT_FOUND    -24
#define AL_NO_PRINTER        -25
#define AL_LOW_RESOLUTION    -26
#define AL_EXIT_CODE         -30
#define AL_NOENT             -31
#define AL_NOMEM             -32
#define AL_NOEXEC            -33
#define AL_EXIT_CODE2        -34
#define AL_BUS_ERROR         -35
#define AL_ADDR_ERROR        -36
#define AL_ILLEGAL_INST      -37
#define AL_ZERO_DIVIDE       -38
#define AL_CHK_INST          -39
#define AL_OVERFLOW_EXC      -40
#define AL_PRIVILEGE_VIO     -41
#define AL_EXCEPTION_FRAME   -42
#define AL_TRAP0             -43
#define AL_TRAP3             -44
#define AL_TRAP4             -45
#define AL_TRAP5             -46
#define AL_TRAP6             -47
#define AL_TRAP7             -48
#define AL_TRAP8             -49
#define AL_TRAP9             -50
#define AL_TRAP10            -51
#define AL_TRAP11            -52
#define AL_TRAP12            -53
#define AL_TRAP15            -54
#define AL_FPU_UNORDERED     -60
#define AL_FPU_INEXACT       -61
#define AL_FPU_ZERO_DIVIDE   -62
#define AL_FPU_UNDERFLOW     -63
#define AL_FPU_OPERAND       -64
#define AL_FPU_OVERFLOW      -65
#define AL_FPU_SNAN          -66
#define AL_MMU_CONFIG        -67
#define AL_MMU_ILLEGAL       -68
#define AL_MMU_ACCESS        -69
#define AL_STACK_OVERFLOW    -70
#define AL_NO_PASM           -100
#define AL_NO_DEBUGGER       -101
#define AL_NO_SHELL          -104
#define AL_NO_USER_SCREEN    -105
#define AL_NO_PASM_RESIDENT  -106
#define AL_INVALID_PDB       -200
#define AL_STACKOVERFLOW     -998
#define AL_DAMAGED_PC        -999
